### ISSUE TITLE
LoadStoneNightly causes issues with LCSoundTool installed

### ISSUE THREAD

**Issue by Test-Account666** [AdalynBlack/Loadstone#11]
Hello!

I noticed that LoadStoneNightly breaks the entire game with LCSoundTool installed.

I also figured out why:
LoadStoneNightly tries to load an audio file from the directory `AdiBTW-Loadstone`.
This fails as the directory is called `AdiBTW-LoadstoneNightly`.

This always breaks the game - What you configured in the config doesn't matter

**Comment by AdalynBlack** [comment]
Yeah, I realized this last night. The automatic renaming I set up was a bit bugged because it didn't run early enough. I've since fixed that, but I haven't uploaded the changes yet. I'll upload a new version soon

**Comment by AdalynBlack** [comment]
Fixed in v0.1.8
