### ISSUE TITLE
Confused About Loadstone & LoadstoneNightly

### ISSUE THREAD

**Issue by LifelikeRylie** [AdalynBlack/Loadstone#12]
I'm just wondering what the difference is between Loadstone and LoadstoneNightly?

Idk if I'm just blind or dum but I can't see any differences to these in the readme (other than LoadstoneNightly not asking for support at the bottom).

**Comment by AdalynBlack** [comment]
Nightly is effectively a beta. It has a couple small tweaks, as well as the ability to toggle some experimental features

**Comment by LifelikeRylie** [comment]
Thanks! I was just wondering.
