### ISSUE TITLE
Can it be compatible with LethalPerformance? Combining the LP and Loadstone is a great optimization combination.

### ISSUE THREAD

**Issue by NakiriFox** [AdalynBlack/Loadstone#18]
[Error  : Loadstone(Harmony)] The assembly "LethalPerformance" has patched the method "Void Start()" with a transpiler using "System.Collections.Generic.IEnumerable`1[HarmonyLib.CodeInstruction] ReplaceFindObjectOfTypeTranspiler(System.Collections.Generic.IEnumerable`1[HarmonyLib.CodeInstruction])", which we also modify. Unexpected behaviour may occur

[Warning: Loadstone(Harmony)] The assembly "HDLethalCompanyRemake" has patched the method "Void GenerateNewFloor()" with a prefix using "Void RoundPostFix()", which we also modify. Unexpected behaviour may occur

**Comment by AdalynBlack** [comment]
Loadstone is actually compatible with Lethal Performance
That message exists just to make it clear that there's a potential for conflict, but it doesn't actually verify whether or not there's an issue. DiFFoZ has already ensured compatibility between the two mods

**Comment by NakiriFox** [comment]
thank you :)
