### ISSUE TITLE
[Suggestion] Music Whilst Loading

### ISSUE THREAD

**Issue by ChloeDawn** [AdalynBlack/Loadstone#3]
An option to play music such as elevator music whilst asynchronously loading would be fun

**Comment by AdalynBlack** [comment]
I could definitely do that
I've been trying to decide what to do about the sometimes long and awkward loading times, and perhaps that would help
I'm also thinking about adding a progress bar somewhere so you can track the load progress and tell if it's stuck or just taking a while

**Comment by AdalynBlack** [comment]
This feature is now implemented
you'll need to install LCSoundTool and enable it in the config for it to work. I have it off by default under the assumption that the majority of people will have load times too short for the loading music to make sense, while still being available for those who wish to have it
