### ISSUE TITLE
Loadstone takes up a lot of space

### ISSUE THREAD

**Issue by LimeSkillZ** [AdalynBlack/Loadstone#6]
This isn't really a huge issue because you can just use version 0.0.3, but the sound file included in the latest version takes up way more space than it needs to. You can create a .ogg file that reduces the filesize from 48 MB to 2.3 MB and sounds about the same.

[Example .ogg file (discord cdn link)](https://cdn.discordapp.com/attachments/602206101915828225/1229136370157486242/LoadstoneLoading.ogg?ex=662e9572&is=661c2072&hm=30ebde8bb63815a7e0234bff0db7994f021560c2d4958592769caac4188041cd&)

**Comment by AdalynBlack** [comment]
oh yeah sure, I can change that
tbh I just used `yt-dlp -x` and called it a day lol

**Comment by AdalynBlack** [comment]
I have converted the audio file to a .wav and uploaded the change to Thunderstore. The file size is now just 3.3 MB
