### ISSUE TITLE
Nightly version, Nightly bugs

### ISSUE THREAD

**Issue by CoolLKKPS** [AdalynBlack/Loadstone#8]
*deleted due error*

**Comment by CoolLKKPS** [comment]
seems like conflict with toomanyemote

**Comment by AdalynBlack** [comment]
Github is saying that the log file is not found
could you try uploading it again?

**Comment by CoolLKKPS** [comment]
uh... idk what happen but i deleted the original one, only backup remain i think, let me check

**Comment by CoolLKKPS** [comment]
[Player.zip](https://github.com/user-attachments/files/15823334/Player.zip)

**Comment by CoolLKKPS** [comment]
don't lost that again, i will delete this log file soon

**Comment by AdalynBlack** [comment]
oh, I think I see the issue
I forgot to make the music search the right folder for nightly 🤦

**Comment by AdalynBlack** [comment]
ok, Loadstone Nightly v0.1.1 just got uploaded, and should fix the issue
v0.1.1 also adds in a few new optimizations to help out with performance and stutters

**Comment by CoolLKKPS** [comment]
ok uh i will test that tomorrow

**Comment by CoolLKKPS** [comment]
uh......

**Comment by CoolLKKPS** [comment]
should be fixed

**Comment by CoolLKKPS** [comment]
@AdalynBlack but still u need to improve navmesh feature (idk how that call now), many `navmesh does not read access` spamming in my log console

**Comment by AdalynBlack** [comment]
Is it talking about meshes that have read/write access disabled? I think that's an issue with modded moons and interiors. Vanilla has it too, but it's only like 2-4 per load in. I might be able to disable the messages to reduce log spam, but it's still indicative of an issue
